version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: clientes-frontend-dev
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8080
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - frontend-dev-network

networks:
  frontend-dev-network:
    driver: bridge
